/**
 * File Auto-Generated by the RICADO Gen 4 PHP API Project
 * 
 * Do Not Edit this File Manually!
 */

/**
 * @namespace DataItems
 */
import PointValueItem from './PointValueItem';

const DataItems = {
    PointValueItem,
};

export default DataItems;