/**
 * File Auto-Generated by the RICADO Gen 4 PHP API Project
 * 
 * Do Not Edit this File Manually!
 */

/**
 * @namespace Controllers.Lab
 */
import Site from './Site/index';

const Lab = {
    Site,
};

export default Lab;