/**
 * File Auto-Generated by the RICADO Gen 4 PHP API Project
 * 
 * Do Not Edit this File Manually!
 */

/**
 * @namespace Controllers.RTU
 */
import GlobalSettingsController from './GlobalSettingsController';
import PluginSettingsController from './PluginSettingsController';

const RTU = {
    GlobalSettingsController,
    PluginSettingsController,
};

export default RTU;