/**
 * File Auto-Generated by the RICADO Gen 4 PHP API Project
 * 
 * Do Not Edit this File Manually!
 */

/**
 * @namespace Controllers.Packhouse.Integrations
 */
import ExternalShiftManagementController from './ExternalShiftManagementController';

const Integrations = {
    ExternalShiftManagementController,
};

export default Integrations;