/**
 * File Auto-Generated by the RICADO Gen 4 PHP API Project
 * 
 * Do Not Edit this File Manually!
 */

/**
 * @namespace Controllers.Packhouse
 */
import ProductionDataExportController from './ProductionDataExportController';
import Integrations from './Integrations/index';
import Site from './Site/index';

const Packhouse = {
    ProductionDataExportController,
    Integrations,
    Site,
};

export default Packhouse;