/**
 * File Auto-Generated by the RICADO Gen 4 PHP API Project
 * 
 * Do Not Edit this File Manually!
 */

/**
 * @namespace Controllers
 */
import AccountPolicyController from './AccountPolicyController';
import ApiAccountController from './ApiAccountController';
import CompanyController from './CompanyController';
import FirebaseTokenController from './FirebaseTokenController';
import RTUController from './RTUController';
import RTUPluginController from './RTUPluginController';
import SiteController from './SiteController';
import TokenController from './TokenController';
import ToolsController from './ToolsController';
import UserAccountActionTokenController from './UserAccountActionTokenController';
import UserAccountController from './UserAccountController';

import Packhouse from './Packhouse';
import RTU from './RTU';
import Site from './Site';

const Controllers = {
    AccountPolicyController,
    ApiAccountController,
    CompanyController,
    FirebaseTokenController,
    RTUController,
    RTUPluginController,
    SiteController,
    TokenController,
    ToolsController,
    UserAccountActionTokenController,
    UserAccountController,
    Packhouse,
    RTU,
    Site,
};

export default Controllers;