/**
 * File Auto-Generated by the RICADO Gen 4 PHP API Project
 * 
 * Do Not Edit this File Manually!
 */

/**
 * The Abstract **BaseModel** Class
 * 
 * @class
 * @abstract
 * @hideconstructor
 */
class BaseModel
{
    /**
     * BaseModel Constructor
     * 
     * @protected
     */
    constructor()
    {
    }
}

export default BaseModel;