/**
 * File Auto-Generated by the RICADO Gen 4 PHP API Project
 * 
 * Do Not Edit this File Manually!
 */

/**
 * The Abstract **BaseModel** Class
 * @abstract
 * @hideconstructor
 */
class BaseModel
{
    /**
     * BaseModel Constructor
     * 
     * @public
     * @param {Object<string, any>} json The Model Properties
     */
    constructor(json)
    {
        /**
         * The Model Properties
         * 
         * @type {Object<string, any>}
         * @protected
         */
        this._json = json;
    }

    /**
     * The Model ID
     * 
     * @abstract
     * @public
     * @type {number|string}
     */
    get id()
    {
        return this._json.id;
    }

    /**
     * Whether the Model has been deleted
     * 
     * @abstract
     * @public
     * @type {boolean}
     */
    get deleted()
    {
        return this._json.deleted;
    }

    /**
     * When the Model was last updated
     * 
     * @abstract
     * @public
     * @type {Date}
     */
    get updateTimestamp()
    {
        return this._json.updateTimestamp;
    }
}

export default BaseModel;