/**
 * File Auto-Generated by the RICADO Gen 4 PHP API Project
 * 
 * Do Not Edit this File Manually!
 */

/**
 * The Abstract **BaseModel** Class
 * @abstract
 * @hideconstructor
 */
class BaseModel
{
    /**
     * BaseModel Constructor
     * 
     * @public
     * @param {Object<string, any>} json The Model Properties
     */
    constructor(json)
    {
        /**
         * The Model Properties
         * 
         * @type {Object<string, any>}
         * @protected
         */
        this._json = json;
    }
}

export default BaseModel;