/**
 * File Auto-Generated by the RICADO Gen 4 PHP API Project
 * 
 * Do Not Edit this File Manually!
 */

import BaseModel from '../Models/BaseModel';

/**
 * Model Class for a Company
 * 
 * @class
 * @hideconstructor
 * @extends BaseModel
 */
class CompanyModel extends BaseModel
{
    /**
     * CompanyModel Constructor
     * 
     * @protected
     */
    constructor()
    {
        super();
        
        /**
         * The Company ID
         * 
         * @type {string}
         * @private
         */
        this._id = undefined;
        
        /**
         * The Company Display Name
         * 
         * @type {string}
         * @private
         */
        this._displayName = undefined;
        
        /**
         * The Company Legal Name
         * 
         * @type {string}
         * @private
         */
        this._legalName = undefined;
        
        /**
         * Whether the Company has been deleted
         * 
         * @type {boolean}
         * @private
         */
        this._deleted = undefined;
        
        /**
         * When the Company was last updated
         * 
         * @type {Date}
         * @private
         */
        this._updateTimestamp = undefined;
    }

    /**
     * The Company ID
     * 
     * @public
     * @type {string}
     */
    get id()
    {
        return this._id;
    }

    /**
     * The Company Display Name
     * 
     * @public
     * @type {string}
     */
    get displayName()
    {
        return this._displayName;
    }

    /**
     * The Company Legal Name
     * 
     * @public
     * @type {string}
     */
    get legalName()
    {
        return this._legalName;
    }

    /**
     * Whether the Company has been deleted
     * 
     * @public
     * @type {boolean}
     */
    get deleted()
    {
        return this._deleted;
    }

    /**
     * When the Company was last updated
     * 
     * @public
     * @type {Date}
     */
    get updateTimestamp()
    {
        return this._updateTimestamp;
    }

    /**
     * Create a new **CompanyModel** from a JSON Object or JSON String
     * 
     * @static
     * @public
     * @param {Object<string, any>|string} json A JSON Object or JSON String
     * @return {CompanyModel}
     */
    static fromJSON(json)
    {
        let model = new CompanyModel();
        
        /**
         * The JSON Object
         * 
         * @type {Object<string, any>}
         */
        let jsonObject = {};
        
        if(typeof json === 'string')
        {
            jsonObject = JSON.parse(json);
        }
        else if(typeof json === 'object')
        {
            jsonObject = json;
        }
        
        if('id' in jsonObject)
        {
            model._id = (function(){
                if(typeof jsonObject['id'] !== 'string')
                {
                    return String(jsonObject['id']);
                }
        
                return jsonObject['id'];
            }());
        }
        
        if('displayName' in jsonObject)
        {
            model._displayName = (function(){
                if(typeof jsonObject['displayName'] !== 'string')
                {
                    return String(jsonObject['displayName']);
                }
        
                return jsonObject['displayName'];
            }());
        }
        
        if('legalName' in jsonObject)
        {
            model._legalName = (function(){
                if(typeof jsonObject['legalName'] !== 'string')
                {
                    return String(jsonObject['legalName']);
                }
        
                return jsonObject['legalName'];
            }());
        }
        
        if('deleted' in jsonObject)
        {
            model._deleted = (function(){
                if(typeof jsonObject['deleted'] !== 'boolean')
                {
                    return Boolean(jsonObject['deleted']);
                }
        
                return jsonObject['deleted'];
            }());
        }
        
        if('updateTimestamp' in jsonObject)
        {
            model._updateTimestamp = (function(){
                if(typeof jsonObject['updateTimestamp'] !== 'string')
                {
                    return new Date(String(jsonObject['updateTimestamp']));
                }
        
                return new Date(jsonObject['updateTimestamp']);
            }());
        }
        
        return model;
    }
}

export default CompanyModel;