/**
 * File Auto-Generated by the RICADO Gen 4 PHP API Project
 * 
 * Do Not Edit this File Manually!
 */

import BaseModel from '../Models/BaseModel';
import CompanyController from '../Controllers/CompanyController';

/**
 * Model Class for a Company
 * @hideconstructor
 * @extends BaseModel
 */
class CompanyModel extends BaseModel
{
    /**
     * CompanyModel Constructor
     * 
     * @public
     * @param {Object<string, any>} json The Company Properties
     */
    constructor(json)
    {
        super(json);
        
        /**
         * The Properties to Update for a Company
         * 
         * @type {Object<string, any>}
         * @private
         */
        this._updateJson = {};
    }

    /**
     * The Company ID
     * 
     * @public
     * @type {string}
     */
    get id()
    {
        return this._json.id;
    }

    /**
     * The Company Display Name
     * 
     * @public
     * @type {string}
     */
    get displayName()
    {
        return this._json.displayName;
    }

    /**
     * The Company Display Name
     * 
     * @public
     * @type {string}
     */
    set displayName(value)
    {
        this._json.displayName = value;
        this._updateJson.displayName = value;
    }

    /**
     * The Company Legal Name
     * 
     * @public
     * @type {string}
     */
    get legalName()
    {
        return this._json.legalName;
    }

    /**
     * The Company Legal Name
     * 
     * @public
     * @type {string}
     */
    set legalName(value)
    {
        this._json.legalName = value;
        this._updateJson.legalName = value;
    }

    /**
     * Whether the Company has been deleted
     * 
     * @public
     * @type {boolean}
     */
    get deleted()
    {
        return this._json.deleted;
    }

    /**
     * When the Company was last updated
     * 
     * @public
     * @type {Date}
     */
    get updateTimestamp()
    {
        return this._json.updateTimestamp;
    }

    /**
     * Update this **Company**
     * 
     * @public
     * @return {Promise<boolean>}
     */
    update()
    {
        return new Promise((resolve, reject) => {
            CompanyController.update(this._json.id, this._updateJson)
            .then((modelResult) => {
                // TODO: Validate the Model Result, Replace everything in this Model with the Model Result, Return True
                
                resolve(true);
            })
            .catch(error => reject(error));
        });
    }

    /**
     * Delete this **Company**
     * 
     * @public
     * @return {Promise<boolean>}
     */
    delete()
    {
        return CompanyController.delete(this._json.id);
    }
}

export default CompanyModel;