/**
 * File Auto-Generated by the RICADO Gen 4 PHP API Project
 * 
 * Do Not Edit this File Manually!
 */

import BaseModel from '../Models/BaseModel';
import FirebaseTokenController from '../Controllers/FirebaseTokenController';

/**
 * Model Class for a Firebase Token
 * @hideconstructor
 * @extends BaseModel
 */
class FirebaseTokenModel extends BaseModel
{
    /**
     * FirebaseTokenModel Constructor
     * 
     * @public
     * @param {Object<string, any>} json The Firebase Token Properties
     */
    constructor(json)
    {
        super(json);
        
        /**
         * The Properties to Update for a Firebase Token
         * 
         * @type {Object<string, any>}
         * @private
         */
        this._updateJson = {};
    }

    /**
     * The Firebase Token ID
     * 
     * @public
     * @type {string}
     */
    get id()
    {
        return this._json.id;
    }

    /**
     * The Account this Firebase Token belongs to
     * 
     * @public
     * @type {string}
     */
    get accountId()
    {
        return this._json.accountId;
    }

    /**
     * The Account this Firebase Token belongs to
     * 
     * @public
     * @type {string}
     */
    set accountId(value)
    {
        this._json.accountId = value;
        this._updateJson.accountId = value;
    }

    /**
     * The Firebase Token
     * 
     * @public
     * @type {string}
     */
    get token()
    {
        return this._json.token;
    }

    /**
     * Whether the Firebase Token should receive Notifications
     * 
     * @public
     * @type {boolean}
     */
    get enabled()
    {
        return this._json.enabled;
    }

    /**
     * Whether the Firebase Token should receive Notifications
     * 
     * @public
     * @type {boolean}
     */
    set enabled(value)
    {
        this._json.enabled = value;
        this._updateJson.enabled = value;
    }

    /**
     * Whether the Firebase Token has been deleted
     * 
     * @public
     * @type {boolean}
     */
    get deleted()
    {
        return this._json.deleted;
    }

    /**
     * When the Firebase Token was last updated
     * 
     * @public
     * @type {Date}
     */
    get updateTimestamp()
    {
        return this._json.updateTimestamp;
    }

    /**
     * Update this **Firebase Token**
     * 
     * @public
     * @return {Promise<boolean>}
     */
    update()
    {
        return new Promise((resolve, reject) => {
            FirebaseTokenController.update(this._json.id, this._updateJson)
            .then((modelResult) => {
                // TODO: Validate the Model Result, Replace everything in this Model with the Model Result, Return True
                
                resolve(true);
            })
            .catch(error => reject(error));
        });
    }

    /**
     * Delete this **Firebase Token**
     * 
     * @public
     * @return {Promise<boolean>}
     */
    delete()
    {
        return FirebaseTokenController.delete(this._json.id);
    }
}

export default FirebaseTokenModel;