/**
 * File Auto-Generated by the RICADO Gen 4 PHP API Project
 * 
 * Do Not Edit this File Manually!
 */

/**
 * @namespace Models
 */
import AccountPolicyModel from './AccountPolicyModel';
import ApiAccountModel from './ApiAccountModel';
import BaseModel from './BaseModel';
import CompanyModel from './CompanyModel';
import FirebaseTokenModel from './FirebaseTokenModel';
import RTUModel from './RTUModel';
import RTUPluginModel from './RTUPluginModel';
import SiteModel from './SiteModel';
import TokenModel from './TokenModel';
import UserAccountActionTokenModel from './UserAccountActionTokenModel';
import UserAccountModel from './UserAccountModel';
import Lab from './Lab/index';
import Packhouse from './Packhouse/index';
import Site from './Site/index';

const Models = {
    AccountPolicyModel,
    ApiAccountModel,
    BaseModel,
    CompanyModel,
    FirebaseTokenModel,
    RTUModel,
    RTUPluginModel,
    SiteModel,
    TokenModel,
    UserAccountActionTokenModel,
    UserAccountModel,
    Lab,
    Packhouse,
    Site,
};

export default Models;