/**
 * File Auto-Generated by the RICADO Gen 4 PHP API Project
 * 
 * Do Not Edit this File Manually!
 */

import BaseModel from '../Models/BaseModel';
import RTUController from '../Controllers/RTUController';

/**
 * Model Class for a RTU
 * @hideconstructor
 * @extends BaseModel
 */
class RTUModel extends BaseModel
{
    /**
     * RTUModel Constructor
     * 
     * @public
     * @param {Object<string, any>} json The RTU Properties
     */
    constructor(json)
    {
        super(json);
        
        /**
         * The Properties to Update for a RTU
         * 
         * @type {Object<string, any>}
         * @private
         */
        this._updateJson = {};
    }

    /**
     * The RTU ID
     * 
     * @public
     * @type {number}
     */
    get id()
    {
        return this._json.id;
    }

    /**
     * The Site this RTU belongs to
     * 
     * @public
     * @type {number}
     */
    get siteId()
    {
        return this._json.siteId;
    }

    /**
     * The RTU Name
     * 
     * @public
     * @type {string}
     */
    get name()
    {
        return this._json.name;
    }

    /**
     * The RTU Name
     * 
     * @public
     * @type {string}
     */
    set name(value)
    {
        this._json.name = value;
        this._updateJson.name = value;
    }

    /**
     * Whether the RTU is Enabled
     * 
     * @public
     * @type {boolean}
     */
    get enabled()
    {
        return this._json.enabled;
    }

    /**
     * Whether the RTU is Enabled
     * 
     * @public
     * @type {boolean}
     */
    set enabled(value)
    {
        this._json.enabled = value;
        this._updateJson.enabled = value;
    }

    /**
     * Whether the RTU has been deleted
     * 
     * @public
     * @type {boolean}
     */
    get deleted()
    {
        return this._json.deleted;
    }

    /**
     * When the RTU was last updated
     * 
     * @public
     * @type {Date}
     */
    get updateTimestamp()
    {
        return this._json.updateTimestamp;
    }

    /**
     * Update this **RTU**
     * 
     * @public
     * @return {Promise<boolean>}
     */
    update()
    {
        return new Promise((resolve, reject) => {
            RTUController.update(this._json.id, this._updateJson)
            .then((modelResult) => {
                // TODO: Validate the Model Result, Replace everything in this Model with the Model Result, Return True
                
                resolve(true);
            })
            .catch(error => reject(error));
        });
    }

    /**
     * Delete this **RTU**
     * 
     * @public
     * @return {Promise<boolean>}
     */
    delete()
    {
        return RTUController.delete(this._json.id);
    }
}

export default RTUModel;