/**
 * File Auto-Generated by the RICADO Gen 4 PHP API Project
 * 
 * Do Not Edit this File Manually!
 */

import BaseModel from '../Models/BaseModel';
import UserAccountController from '../Controllers/UserAccountController';

/**
 * Model Class for a User Account
 * @hideconstructor
 * @extends BaseModel
 */
class UserAccountModel extends BaseModel
{
    /**
     * UserAccountModel Constructor
     * 
     * @public
     * @param {Object<string, any>} json The User Account Properties
     */
    constructor(json)
    {
        super(json);
        
        /**
         * The Properties to Update for a User Account
         * 
         * @type {Object<string, any>}
         * @private
         */
        this._updateJson = {};
    }

    /**
     * The User Account ID
     * 
     * @public
     * @type {string}
     */
    get id()
    {
        return this._json.id;
    }

    /**
     * The User's Email Address
     * 
     * @public
     * @type {string}
     */
    get email()
    {
        return this._json.email;
    }

    /**
     * The User's Email Address
     * 
     * @public
     * @type {string}
     */
    set email(value)
    {
        this._json.email = value;
        this._updateJson.email = value;
    }

    /**
     * The User's First Name
     * 
     * @public
     * @type {?string}
     */
    get firstName()
    {
        return this._json.firstName;
    }

    /**
     * The User's First Name
     * 
     * @public
     * @type {?string}
     */
    set firstName(value)
    {
        this._json.firstName = value;
        this._updateJson.firstName = value;
    }

    /**
     * The User's Last Name
     * 
     * @public
     * @type {?string}
     */
    get lastName()
    {
        return this._json.lastName;
    }

    /**
     * The User's Last Name
     * 
     * @public
     * @type {?string}
     */
    set lastName(value)
    {
        this._json.lastName = value;
        this._updateJson.lastName = value;
    }

    /**
     * The Company this User belongs to
     * 
     * @public
     * @type {string}
     */
    get companyId()
    {
        return this._json.companyId;
    }

    /**
     * Whether the User Account has been deleted
     * 
     * @public
     * @type {boolean}
     */
    get deleted()
    {
        return this._json.deleted;
    }

    /**
     * When the User Account was last updated
     * 
     * @public
     * @type {Date}
     */
    get updateTimestamp()
    {
        return this._json.updateTimestamp;
    }

    /**
     * Update this **User Account**
     * 
     * @public
     * @return {Promise<boolean>}
     */
    update()
    {
        return new Promise((resolve, reject) => {
            UserAccountController.update(this._json.id, this._updateJson)
            .then((modelResult) => {
                // TODO: Validate the Model Result, Replace everything in this Model with the Model Result, Return True
                
                resolve(true);
            })
            .catch(error => reject(error));
        });
    }

    /**
     * Delete this **User Account**
     * 
     * @public
     * @return {Promise<boolean>}
     */
    delete()
    {
        return UserAccountController.delete(this._json.id);
    }
}

export default UserAccountModel;