/**
 * File Auto-Generated by the RICADO Gen 4 PHP API Project
 * 
 * Do Not Edit this File Manually!
 */

import BaseModel from '../Models/BaseModel';
import UserAccountController from '../Controllers/UserAccountController';

/**
 * Model Class for a User Account
 * @hideconstructor
 * @extends BaseModel
 */
class UserAccountModel extends BaseModel
{
    /**
     * UserAccountModel Constructor
     * 
     * @public
     * @param {Object<string, any>} json The User Account Properties
     */
    constructor(json)
    {
        super(json);
    }

    /**
     * The User Account ID
     * 
     * @public
     * @type {string}
     */
    get id()
    {
        return this._json.id;
    }

    /**
     * The User's Email Address
     * 
     * @public
     * @type {string}
     */
    get email()
    {
        return this._json.email;
    }

    /**
     * The User's First Name
     * 
     * @public
     * @type {?string}
     */
    get firstName()
    {
        return this._json.firstName;
    }

    /**
     * The User's Last Name
     * 
     * @public
     * @type {?string}
     */
    get lastName()
    {
        return this._json.lastName;
    }

    /**
     * The Company this User belongs to
     * 
     * @public
     * @type {string}
     */
    get companyId()
    {
        return this._json.companyId;
    }

    /**
     * Whether the User Account has been deleted
     * 
     * @public
     * @type {boolean}
     */
    get deleted()
    {
        return this._json.deleted;
    }

    /**
     * When the User Account was last updated
     * 
     * @public
     * @type {Date}
     */
    get updateTimestamp()
    {
        return this._json.updateTimestamp;
    }
}

export default UserAccountModel;