/**
 * @module ricado-gen4-api-client
 * 
 * The RICADO Gen 4 API Client for NodeJS and Browsers
 */

// Export the API Class as our Default Module Class
import API from './API';

API.prototype.JWT = 'hello';

export default API;

/**
 * The Base URL for the RICADO Gen 4 API
 * 
 * @type {string}
 */
//export const BaseURL = "https://api-dev.ricado.co.nz/api/4.0";
export const BaseURL = "http://localhost:8888";

/**
 * A List of Paths (Relative URLs) that do not require Authentication
 * 
 * @type {Array}
 */
export const NoAuthPaths = ['/ping','/token/new']; // TODO: This should really be generated by our PHP API script since this could change without us knowing!!

/**
 * The JSON Web Token for all Authenticated API Calls
 * 
 * @type {string}
 */

//export var JWT = null;