/**
 * File Auto-Generated by the RICADO Gen 4 PHP API Project
 * 
 * Do Not Edit this File Manually!
 */

/**
 * An Array of Paths (Relative URLs) that do not require Authentication
 * @type {string[]}
*/
const NoAuthPaths = ['/token/new','/ping','/user-action-tokens/new','/user-action-tokens/verify','/user-action-tokens/actions/*','/openapi.json'];

export default NoAuthPaths;