# Action Name
name: GitHub Pages

# Controls when the action will run
# TODO: Remove the master and api-generation-upgrade Branches once we've merged in
on:
  push:
    branches:
      - master
      - api-generation-upgrade
    tags:
      - "*.*.*"

# Workflow Jobs
jobs:
  # Deploy Job
  deploy:
    # Job Runner
    runs-on: ubuntu-latest

    # Job Steps
    steps:
      # Step 1 - Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2
      
      # Step 2 - Setup NodeJS
      - name: Setup NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true
      
      # Step 3 - Install NPM Packages
      - name: Install NPM Packages
        run: npm ci

      # Step 4 - Build the Docs
      - name: Build Docs
        run: npm run docs

      # Step 5 - Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
