name: 'Pull Request - Merge'

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  merge:
    uses: ricado-group/common-workflows/.github/workflows/pr-merge.yml@v1
    with:
      projectType: |
        npm
      gra-app-client-id: ${{ vars.GRA_APP_CLIENT_ID }}
    secrets:
      gra-app-private-key: ${{ secrets.GRA_APP_PRIVATE_KEY }}
